
 const VOCAB_ALL = [
// --- NOUNS (Substantivos) ---
{ q: "Water", a: "Água", type: "noun" },
{ q: "Sky", a: "Céu", type: "noun" },
{ q: "Apple", a: "Maçã", type: "noun" },
{ q: "Book", a: "Livro", type: "noun" },
{ q: "Sun", a: "Sol", type: "noun" },
{ q: "Moon", a: "Lua", type: "noun" },
{ q: "House", a: "Casa", type: "noun" },
{ q: "Dog", a: "Cachorro", type: "noun" },
{ q: "Cat", a: "Gato", type: "noun" },
{ q: "Car", a: "Carro", type: "noun" },
{ q: "Tree", a: "Árvore", type: "noun" },
{ q: "Food", a: "Comida", type: "noun" },
{ q: "Friend", a: "Amigo", type: "noun" },
{ q: "Family", a: "Família", type: "noun" },
{ q: "School", a: "Escola", type: "noun" },
{ q: "Work", a: "Trabalho", type: "noun" },
{ q: "City", a: "Cidade", type: "noun" },
{ q: "Street", a: "Rua", type: "noun" },
{ q: "Door", a: "Porta", type: "noun" },
{ q: "Window", a: "Janela", type: "noun" },
{ q: "Table", a: "Mesa", type: "noun" },
{ q: "Chair", a: "Cadeira", type: "noun" },
{ q: "Bed", a: "Cama", type: "noun" },
{ q: "Phone", a: "Telefone", type: "noun" },
{ q: "Computer", a: "Computador", type: "noun" },
{ q: "Game", a: "Jogo", type: "noun" },
{ q: "Music", a: "Música", type: "noun" },
{ q: "Movie", a: "Filme", type: "noun" },
{ q: "Time", a: "Tempo", type: "noun" },
{ q: "Day", a: "Dia", type: "noun" },
{ q: "Night", a: "Noite", type: "noun" },
{ q: "Morning", a: "Manhã", type: "noun" },
{ q: "Love", a: "Amor", type: "noun" },
{ q: "Money", a: "Dinheiro", type: "noun" },
{ q: "Job", a: "Emprego", type: "noun" },
{ q: "Boss", a: "Chefe", type: "noun" },
{ q: "Teacher", a: "Professor", type: "noun" },
{ q: "Student", a: "Estudante", type: "noun" },
{ q: "Man", a: "Homem", type: "noun" },
{ q: "Woman", a: "Mulher", type: "noun" },
{ q: "Child", a: "Criança", type: "noun" },
{ q: "Baby", a: "Bebê", type: "noun" },
{ q: "Waterfall", a: "Cachoeira", type: "noun" },
{ q: "River", a: "Rio", type: "noun" },
{ q: "Sea", a: "Mar", type: "noun" },
{ q: "Beach", a: "Praia", type: "noun" },
{ q: "Mountain", a: "Montanha", type: "noun" },
{ q: "People", a: "Pessoas", type: "noun" },
{ q: "Thing", a: "Coisa", type: "noun" },
{ q: "Place", a: "Lugar", type: "noun" },
{ q: "Way", a: "Caminho", type: "noun" },
 { q: "phone", a: "celular", type: "noun" },
{ q: "computer", a: "computador", type: "noun" },
{ q: "keyboard", a: "teclado", type: "noun" },
{ q: "mouse", a: "mouse", type: "noun" },
{ q: "screen", a: "tela", type: "noun" },
{ q: "table", a: "mesa", type: "noun" },
{ q: "chair", a: "cadeira", type: "noun" },
{ q: "bed", a: "cama", type: "noun" },
{ q: "door", a: "porta", type: "noun" },
{ q: "window", a: "janela", type: "noun" },
{ q: "lamp", a: "lâmpada", type: "noun" },
{ q: "book", a: "livro", type: "noun" },
{ q: "pen", a: "caneta", type: "noun" },
{ q: "notebook", a: "caderno", type: "noun" },
{ q: "bag", a: "bolsa/mochila", type: "noun" },
{ q: "wallet", a: "carteira", type: "noun" },
{ q: "key", a: "chave", type: "noun" },
{ q: "clock", a: "relógio", type: "noun" },
{ q: "watch", a: "relógio de pulso", type: "noun" },
{ q: "cup", a: "copo/xícara", type: "noun" },
{ q: "bottle", a: "garrafa", type: "noun" },
{ q: "plate", a: "prato", type: "noun" },
{ q: "spoon", a: "colher", type: "noun" },
{ q: "fork", a: "garfo", type: "noun" },
{ q: "knife", a: "faca", type: "noun" },
{ q: "food", a: "comida", type: "noun" },
{ q: "water", a: "água", type: "noun" },
{ q: "greet", a: "cumprimentar", type: "verb" },
{ q: "say", a: "dizer", type: "verb" },
{ q: "hello", a: "olá", type: "interjection" },
{ q: "hi", a: "oi", type: "interjection" },
{ q: "good morning", a: "bom dia", type: "interjection" },
{ q: "good afternoon", a: "boa tarde", type: "interjection" },
{ q: "good evening", a: "boa noite (chegada)", type: "interjection" },
{ q: "good night", a: "boa noite (despedida)", type: "interjection" },
{ q: "clothes", a: "roupas", type: "noun" },
{ q: "hello", a: "olá", type: "interjection" },
{ q: "hi", a: "oi", type: "interjection" },
{ q: "hey", a: "ei / oi", type: "interjection" },
{ q: "good morning", a: "bom dia", type: "interjection" },
{ q: "good afternoon", a: "boa tarde", type: "interjection" },
{ q: "good evening", a: "boa noite (chegada)", type: "interjection" },
{ q: "good night", a: "boa noite (despedida)", type: "interjection" },

{ q: "wow", a: "uau", type: "interjection" },
{ q: "oh", a: "oh / ah", type: "interjection" },
{ q: "oops", a: "ops", type: "interjection" },
{ q: "uh", a: "uh / hã", type: "interjection" },
{ q: "um", a: "hum / pensando", type: "interjection" },

{ q: "ouch", a: "ai", type: "interjection" },
{ q: "yay", a: "eba", type: "interjection" },
{ q: "ugh", a: "aff / que nojo", type: "interjection" },
{ q: "yuck", a: "eca", type: "interjection" },
{ q: "huh", a: "hã?", type: "interjection" },

{ q: "aha", a: "ahá", type: "interjection" },
{ q: "oh no", a: "ah não", type: "interjection" },
{ q: "bravo", a: "bravo", type: "interjection" },
{ q: "alas", a: "ai de mim", type: "interjection" },

{ q: "hey!", a: "ei! (chamar atenção)", type: "interjection" },
{ q: "shh", a: "psiu", type: "interjection" },
{ q: "psst", a: "psiu (chamar alguém)", type: "interjection" },
{ q: "yo", a: "e aí", type: "interjection" },  
{ q: "shoe", a: "sapato", type: "noun" },
{ q: "shirt", a: "camisa", type: "noun" },

// --- VERBS (Verbos) ---
{ q: "Go", a: "Ir", type: "verb" },
{ q: "Come", a: "Vir", type: "verb" },
{ q: "Do", a: "Fazer", type: "verb" },
{ q: "Make", a: "Criar", type: "verb" },
{ q: "Get", a: "Conseguir", type: "verb" },
{ q: "Give", a: "Dar", type: "verb" },
{ q: "Take", a: "Levar", type: "verb" },
{ q: "Eat", a: "Comer", type: "verb" },
{ q: "Drink", a: "Beber", type: "verb" },
{ q: "Sleep", a: "Dormir", type: "verb" },
{ q: "Wake", a: "Acordar", type: "verb" },
{ q: "See", a: "Ver", type: "verb" },
{ q: "Look", a: "Olhar", type: "verb" },
{ q: "Hear", a: "Ouvir", type: "verb" },
{ q: "Speak", a: "Falar", type: "verb" },
{ q: "Say", a: "Dizer", type: "verb" },
{ q: "Think", a: "Pensar", type: "verb" },
{ q: "Know", a: "Saber", type: "verb" },
{ q: "Understand", a: "Entender", type: "verb" },
{ q: "Want", a: "Querer", type: "verb" },
{ q: "Need", a: "Precisar", type: "verb" },
{ q: "Like", a: "Gostar", type: "verb" },
{ q: "Study", a: "Estudar", type: "verb" },
{ q: "Play", a: "Jogar", type: "verb" },
{ q: "Run", a: "Correr", type: "verb" },
{ q: "Walk", a: "Andar", type: "verb" },
{ q: "Talk", a: "Falar", type: "verb" },
{ q: "Find", a: "Encontrar", type: "verb" },
{ q: "Try", a: "Tentar", type: "verb" },
{ q: "Is", a: "É/Está", type: "verb" },
{ q: "Be", a: "Ser/Estar", type: "verb" },
{ q: "Was", a: "Era/Estava", type: "verb" },
{ q: "Were", a: "Eram/Estavam", type: "verb" },
{ q: "Been", a: "Sido/Estado", type: "verb" },
{ q: "thank", a: "agradecer", type: "verb" },

// --- ADJECTIVES (Adjetivos) ---
{ q: "Good", a: "Bom", type: "adjective" },
{ q: "Bad", a: "Ruim", type: "adjective" },
{ q: "Big", a: "Grande", type: "adjective" },
{ q: "Small", a: "Pequeno", type: "adjective" },
{ q: "Fast", a: "Rápido", type: "adjective" },
{ q: "Slow", a: "Lento", type: "adjective" },
{ q: "Hot", a: "Quente", type: "adjective" },
{ q: "Cold", a: "Frio", type: "adjective" },
{ q: "Easy", a: "Fácil", type: "adjective" },
{ q: "Hard", a: "Difícil", type: "adjective" },
{ q: "Happy", a: "Feliz", type: "adjective" },
{ q: "Sad", a: "Triste", type: "adjective" },
{ q: "New", a: "Novo", type: "adjective" },
{ q: "Old", a: "Velho", type: "adjective" },
{ q: "Strong", a: "Forte", type: "adjective" },
{ q: "Weak", a: "Fraco", type: "adjective" },
{ q: "Very", a: "Muito", type: "adjective" },

// --- PRONOUNS & POSSESSIVES (Pronomes) ---
{ q: "I", a: "Eu", type: "pronoun" },
{ q: "You", a: "Você", type: "pronoun" },
{ q: "He", a: "Ele", type: "pronoun" },
{ q: "She", a: "Ela", type: "pronoun" },
{ q: "We", a: "Nós", type: "pronoun" },
{ q: "They", a: "Eles", type: "pronoun" },
{ q: "This", a: "Isso/Este", type: "pronoun" },
{ q: "That", a: "Aquilo/Aquele", type: "pronoun" },
{ q: "Our", a: "Nosso", type: "possessive" },
{ q: "Their", a: "Deles", type: "possessive" },
{ q: "My", a: "Meu",type: "possessive" },
{ q: "Your", a: "Seu", type: "possessive" },
{ q: "His", a: "Dele", type: "possessive" },
{ q: "Her", a: "Dela", type: "possessive" },
// --- PREPOSITIONS & ARTICLES ---
{ q: "A", a: "Um/Uma", type: "article" },
{ q: "An", a: "Um/Uma (vocal)", type: "article" },
{ q: "The", a: "O/A", type: "article" },
{ q: "At", a: "Em/No/Na", type: "preposition" },
{ q: "In", a: "Em/Dentro", type: "preposition" },
{ q: "On", a: "Em/Sobre", type: "preposition" },
{ q: "Under", a: "Embaixo", type: "preposition" },
{ q: "Above", a: "Acima", type: "preposition" },
{ q: "Below", a: "Abaixo", type: "preposition" },
{ q: "Behind", a: "Atrás", type: "preposition" },
{ q: "Between", a: "Entre (dois)", type: "preposition" },
{ q: "Among", a: "Entre (vários)", type: "preposition" },
{ q: "To", a: "Para", type: "preposition" },
{ q: "From", a: "De/Origem", type: "preposition" },
{ q: "With", a: "Com", type: "preposition" },
{ q: "Without", a: "Sem", type: "preposition" },
{ q: "For", a: "Para/Por", type: "preposition" },
{ q: "About", a: "Sobre", type: "preposition" },
{ q: "Of", a: "De", type: "preposition" },
{ q: "By", a: "Por/Perto", type: "preposition" },
{ q: "After", a: "Depois", type: "preposition" },
{ q: "Before", a: "Antes", type: "preposition" },

// --- OTHERS ---
{ q: "Today", a: "Hoje", type: "other" },
{ q: "Here", a: "Aqui", type: "other" },
{ q: "Why", a: "Por quê", type: "question" },
{ q: "There", a: "Lá", type: "other" },
{ q: "Maybe", a: "Talvez", type: "other" },
{ q: "Yes", a: "Sim", type: "other" },
{ q: "No", a: "Não", type: "other" },
{ q: "What", a: "O quê", type: "question" },
{ q: "Who", a: "Quem", type: "question" },
{ q: "When", a: "Quando", type: "question" },
{ q: "Where", a: "Onde", type: "question" },
{ q: "Why", a: "Por quê", type: "question" },
{ q: "How", a: "Como", type: "question" },
{ q: "Can", a: "Pode/Consegue", type: "modal verb" },
{ q: "Write", a: "Escrever", type: "verb" },
{ q: "Writing", a: "Escrevendo", type: "verb (gerúndio)" },
{ q: "saw", a: "viu", type: "verb" },
{ q: "see", a: "ver", type: "verb" },
{ q: "soon", a: "em breve", type: "adverb" },
{ q: "Could", a: "Podia/Poderia", type: "modal verb" },
{ q: "May", a: "Pode", type: "modal verb" },
{ q: "Might", a: "Poderia", type: "modal verb" },
{ q: "Should", a: "Deveria", type: "modal verb" },
{ q: "Must", a: "Deve/Obrigação", type: "modal verb" },
{ q: "Would", a: "Faria/Iria", type: "modal verb" },
{ q: "Shall", a: "Deverá (formal)", type: "modal verb" },
{ q: "Will", a: "Irá (futuro)", type: "modal verb" },
{ q: "red", a: "vermelho", type: "color" },
{ q: "blue", a: "azul", type: "color" },
{ q: "green", a: "verde", type: "color" },
{ q: "yellow", a: "amarelo", type: "color" },
{ q: "black", a: "preto", type: "color" },
{ q: "white", a: "branco", type: "color" },
{ q: "gray", a: "cinza", type: "color" },
{ q: "orange", a: "laranja", type: "color" },
{ q: "purple", a: "roxo", type: "color" },
{ q: "pink", a: "rosa", type: "color" },
{ q: "brown", a: "marrom", type: "color" },
{ q: "beige", a: "bege", type: "color" },
{ q: "gold", a: "dourado", type: "color" },
{ q: "silver", a: "prata", type: "color" },
{ q: "cyan", a: "ciano", type: "color" },
{ q: "magenta", a: "magenta", type: "color" },
{ q: "navy", a: "azul marinho", type: "color" },
{ q: "teal", a: "verde-azulado", type: "color" },
{ q: "lime", a: "verde limão", type: "color" },
{ q: "indigo", a: "índigo", type: "color" },
{ q: "violet", a: "violeta", type: "color" },
{ q: "turquoise", a: "turquesa", type: "color" },
{ q: "maroon", a: "vinho", type: "color" },
{ q: "olive", a: "verde oliva", type: "color" },
{ q: "coral", a: "coral", type: "color" },
{ q: "salmon", a: "salmão", type: "color" },
{ q: "chocolate", a: "chocolate", type: "color" },
{ q: "ivory", a: "marfim", type: "color" },
{ q: "khaki", a: "caqui", type: "color" },
{ q: "plum", a: "ameixa", type: "color" },
{ q: "Mission", a: "Missão", type: "noun" },
{ q: "Restore", a: "Restaurar", type: "verb" },
{ q: "System", a: "Sistema", type: "noun" },
{ q: "Defend", a: "Defender", type: "verb" },
{ q: "Save", a: "Salvar", type: "verb" },
{ q: "Network", a: "Rede", type: "noun" },
{ q: "Balance", a: "Equilíbrio", type: "noun" },
{ q: "Thoughts", a: "Pensamentos", type: "noun" },
{ q: "one", a: "um", type: "number" },
{ q: "two", a: "dois", type: "number" },
{ q: "three", a: "três", type: "number" },
{ q: "four", a: "quatro", type: "number" },
{ q: "five", a: "cinco", type: "number" },
{ q: "six", a: "seis", type: "number" },
{ q: "seven", a: "sete", type: "number" },
{ q: "eight", a: "oito", type: "number" },
{ q: "nine", a: "nove", type: "number" },
{ q: "ten", a: "dez", type: "number" },

{ q: "eleven", a: "onze", type: "number" },
{ q: "twelve", a: "doze", type: "number" },
{ q: "thirteen", a: "treze", type: "number" },
{ q: "fourteen", a: "catorze", type: "number" },
{ q: "fifteen", a: "quinze", type: "number" },
{ q: "sixteen", a: "dezesseis", type: "number" },
{ q: "seventeen", a: "dezessete", type: "number" },
{ q: "eighteen", a: "dezoito", type: "number" },
{ q: "nineteen", a: "dezenove", type: "number" },
{ q: "twenty", a: "vinte", type: "number" },

{ q: "twenty-one", a: "vinte e um", type: "number" },
{ q: "twenty-two", a: "vinte e dois", type: "number" },
{ q: "twenty-three", a: "vinte e três", type: "number" },
{ q: "twenty-four", a: "vinte e quatro", type: "number" },
{ q: "twenty-five", a: "vinte e cinco", type: "number" },
{ q: "twenty-six", a: "vinte e seis", type: "number" },
{ q: "twenty-seven", a: "vinte e sete", type: "number" },
{ q: "twenty-eight", a: "vinte e oito", type: "number" },
{ q: "twenty-nine", a: "vinte e nove", type: "number" },
{ q: "thirty", a: "trinta", type: "number" },

{ q: "thirty-one", a: "trinta e um", type: "number" },
{ q: "thirty-two", a: "trinta e dois", type: "number" },
{ q: "thirty-three", a: "trinta e três", type: "number" },
{ q: "thirty-four", a: "trinta e quatro", type: "number" },
{ q: "thirty-five", a: "trinta e cinco", type: "number" },
{ q: "thirty-six", a: "trinta e seis", type: "number" },
{ q: "thirty-seven", a: "trinta e sete", type: "number" },
{ q: "thirty-eight", a: "trinta e oito", type: "number" },
{ q: "thirty-nine", a: "trinta e nove", type: "number" },
{ q: "forty", a: "quarenta", type: "number" },

{ q: "forty-one", a: "quarenta e um", type: "number" },
{ q: "forty-two", a: "quarenta e dois", type: "number" },
{ q: "forty-three", a: "quarenta e três", type: "number" },
{ q: "forty-four", a: "quarenta e quatro", type: "number" },
{ q: "forty-five", a: "quarenta e cinco", type: "number" },
{ q: "forty-six", a: "quarenta e seis", type: "number" },
{ q: "forty-seven", a: "quarenta e sete", type: "number" },
{ q: "forty-eight", a: "quarenta e oito", type: "number" },
{ q: "forty-nine", a: "quarenta e nove", type: "number" },
{ q: "fifty", a: "cinquenta", type: "number" },

{ q: "fifty-one", a: "cinquenta e um", type: "number" },
{ q: "fifty-two", a: "cinquenta e dois", type: "number" },
{ q: "fifty-three", a: "cinquenta e três", type: "number" },
{ q: "fifty-four", a: "cinquenta e quatro", type: "number" },
{ q: "fifty-five", a: "cinquenta e cinco", type: "number" },
{ q: "fifty-six", a: "cinquenta e seis", type: "number" },
{ q: "fifty-seven", a: "cinquenta e sete", type: "number" },
{ q: "fifty-eight", a: "cinquenta e oito", type: "number" },
{ q: "fifty-nine", a: "cinquenta e nove", type: "number" },
{ q: "sixty", a: "sessenta", type: "number" },

{ q: "sixty-one", a: "sessenta e um", type: "number" },
{ q: "sixty-two", a: "sessenta e dois", type: "number" },
{ q: "sixty-three", a: "sessenta e três", type: "number" },
{ q: "sixty-four", a: "sessenta e quatro", type: "number" },
{ q: "sixty-five", a: "sessenta e cinco", type: "number" },
{ q: "sixty-six", a: "sessenta e seis", type: "number" },
{ q: "sixty-seven", a: "sessenta e sete", type: "number" },
{ q: "sixty-eight", a: "sessenta e oito", type: "number" },
{ q: "sixty-nine", a: "sessenta e nove", type: "number" },
{ q: "seventy", a: "setenta", type: "number" },

{ q: "seventy-one", a: "setenta e um", type: "number" },
{ q: "seventy-two", a: "setenta e dois", type: "number" },
{ q: "seventy-three", a: "setenta e três", type: "number" },
{ q: "seventy-four", a: "setenta e quatro", type: "number" },
{ q: "seventy-five", a: "setenta e cinco", type: "number" },
{ q: "seventy-six", a: "setenta e seis", type: "number" },
{ q: "seventy-seven", a: "setenta e sete", type: "number" },
{ q: "seventy-eight", a: "setenta e oito", type: "number" },
{ q: "seventy-nine", a: "setenta e nove", type: "number" },
{ q: "eighty", a: "oitenta", type: "number" },

{ q: "eighty-one", a: "oitenta e um", type: "number" },
{ q: "eighty-two", a: "oitenta e dois", type: "number" },
{ q: "eighty-three", a: "oitenta e três", type: "number" },
{ q: "eighty-four", a: "oitenta e quatro", type: "number" },
{ q: "eighty-five", a: "oitenta e cinco", type: "number" },
{ q: "eighty-six", a: "oitenta e seis", type: "number" },
{ q: "eighty-seven", a: "oitenta e sete", type: "number" },
{ q: "eighty-eight", a: "oitenta e oito", type: "number" },
{ q: "eighty-nine", a: "oitenta e nove", type: "number" },
{ q: "ninety", a: "noventa", type: "number" },

{ q: "ninety-one", a: "noventa e um", type: "number" },
{ q: "ninety-two", a: "noventa e dois", type: "number" },
{ q: "ninety-three", a: "noventa e três", type: "number" },
{ q: "ninety-four", a: "noventa e quatro", type: "number" },
{ q: "ninety-five", a: "noventa e cinco", type: "number" },
{ q: "ninety-six", a: "noventa e seis", type: "number" },
{ q: "ninety-seven", a: "noventa e sete", type: "number" },
{ q: "ninety-eight", a: "noventa e oito", type: "number" },
{ q: "ninety-nine", a: "noventa e nove", type: "number" },
{ q: "one hundred", a: "cem", type: "number" },
{ q: "a", a: "um / uma (artigo indefinido)", type: "article" },
{ q: "neural", a: "neural (relacionado ao sistema nervoso/cérebro)", type: "adjective" },
{ q: "virus", a: "vírus", type: "noun" },
{ q: "is", a: "é / está", type: "verb" },
{ q: "erasing", a: "apagando / eliminando", type: "verb" },
{ q: "all", a: "todos", type: "determiner" },
{ q: "human", a: "humano", type: "adjective" },
{ q: "memories", a: "memórias", type: "noun" },
{ q: "last", a: "último", type: "adjective" },
{ q: "Speak", a: "Falar", type: "verb" },
{ q: "hope", a: "esperança", type: "noun" },
{ q: "to", a: "para", type: "preposition" },
{ q: "defend", a: "defender", type: "verb" },
{ q: "the", a: "o / a (artigo definido)", type: "article" },
{ q: "network", a: "rede / sistema de rede", type: "noun" },
{ q: "Minds", a: "mentes", type: "noun" },
{ q: "were", a: "foram / estavam", type: "verb" },
{ q: "imprisoned", a: "aprisionadas", type: "verb" },
{ q: "and", a: "e", type: "conjunction" },
{ q: "our", a: "nosso / nossa", type: "pronoun" },
{ q: "language", a: "linguagem / língua", type: "noun" },
{ q: "was", a: "foi / estava", type: "verb" },
{ q: "stolen", a: "roubada", type: "verb" },
{ q: "But", a: "mas", type: "conjunction" },
{ q: "one", a: "um / uma", type: "number" },
{ q: "small", a: "pequeno", type: "adjective" },
{ q: "mind", a: "mente", type: "noun" },
{ q: "remained", a: "permaneceu / ficou", type: "verb" },
{ q: "free", a: "livre", type: "adjective" },
{ q: "deciphering", a: "decifrando", type: "verb" },
{ q: "the", a: "o / a (artigo definido)", type: "article" },
{ q: "alien", a: "alienígena / estranho", type: "adjective" },
{ q: "code", a: "código", type: "noun" }

];

VOCAB_SENTENCES = [
{ q: "The sky is blue", a: "O céu é azul" },
{ q: "I like to learn", a: "Eu gosto de aprender" },
{ q: "I am happy", a: "Eu estou feliz" },
{ q: "You are here", a: "Você está aqui" },
{ q: "He is my friend", a: "Ele é meu amigo" },
{ q: "She is at home", a: "Ela está em casa" },
{ q: "We are ready", a: "Nós estamos prontos" },
{ q: "They are coming", a: "Eles estão vindo" },
{ q: "I like food", a: "Eu gosto de comida" },
{ q: "I like music", a: "Eu gosto de música" },
{ q: "I like games", a: "Eu gosto de jogos" },
{ q: "I like you", a: "Eu gosto de você" },
{ q: "I need help", a: "Eu preciso de ajuda" },
{ q: "I want water", a: "Eu quero água" },
{ q: "I want food", a: "Eu quero comida" },
{ q: "I see you", a: "Eu vejo você" },
{ q: "I hear you", a: "Eu ouço você" },
{ q: "I am", a: "Eu sou ou estou",},
{ q: "You are", a: "Você é ou está"},
{ q: "He is", a: "Ele é ou está"},
{ q: "She is", a: "Ela é ou está"},
{ q: "It is", a: "Isso é ou está"},
{ q: "We are", a: "Nós somos ou estamos"},
{ q: "They are", a: "Eles são ou estão"},
{ q: "See you soon", a: "Até logo" },
{ q: "Why are you here?", a: "Por que você está aqui?" },
{ q: "Why are you sad?", a: "Por que você está triste?" },
{ q: "Why do you cry?", a: "Por que você chora?" },
{ q: "Why is she angry?", a: "Por que ela está brava?" },
{ q: "Why do they leave?", a: "Por que eles vão embora?" },
{ q: "Why are we waiting?", a: "Por que estamos esperando?" },
{ q: "Why do you ask?", a: "Por que você pergunta?" },
{ q: "Why is it important?", a: "Por que isso é importante?" },
{ q: "Why are you late?", a: "Por que você está atrasado?" },
{ q: "Why not?", a: "Por que não?" },
{ q: "I am tired", a: "Eu estou cansado" },
{ q: "I am ready", a: "Eu estou pronto" },
{ q: "I write", a: "Eu escrevo" },
{ q: "She writes", a: "Ela escreve" },
{ q: "We write together", a: "Nós escrevemos juntos" },
{ q: "They write books", a: "Eles escrevem livros" },
{ q: "Write your name", a: "Escreva seu nome" },
{ q: "Write it down", a: "Escreva isso" },
{ q: "I am writing", a: "Eu estou escrevendo" },
{ q: "Stop writing", a: "Pare de escrever" },
{ q: "Do you ever stop writing?", a: "Você alguma vez para de escrever?" },
{ q: "Why do you stop writing?", a: "Por que você para de escrever?" },
{ q: "I will write", a: "Eu vou escrever" },
{ q: "In front of", a: "na frente de"},
{ q: "I am here", a: "Eu estou aqui" },
{ q: "Next to", a: "ao lado de"},
{ q: "You are right", a: "Você está certo" },
{ q: "You are wrong", a: "Você está errado" },
{ q: "He is strong", a: "Ele é forte" },
{ q: "She is kind", a: "Ela é gentil" },
{ q: "We are friends", a: "Nós somos amigos" },
{ q: "They are happy", a: "Eles estão felizes" },
{ q: "The sun is hot", a: "O sol está quente" },
{ q: "The water is cold", a: "A água está fria" },
{ q: "This is good", a: "Isso é bom" },
{ q: "That is bad", a: "Aquilo é ruim" },
{ q: "I thank you", a: "Eu te agradeço" },
{ q: "She thanks her friend", a: "Ela agradece seu amigo" },
{ q: "We thank God", a: "Nós agradecemos a Deus" },
{ q: "They thank the teacher", a: "Eles agradecem ao professor" },
{ q: "He thanks his mother", a: "Ele agradece sua mãe" },
{ q: "Come with me", a: "Venha comigo" },
{ q: "Go with me", a: "Vá comigo" },
{ q: "Open the door", a: "Abra a porta" },
{ q: "Close the door", a: "Feche a porta" },
{ q: "Sit here", a: "Sente aqui" },
{ q: "Stand up", a: "Levante-se" },
{ q: "Look at me", a: "Olhe para mim" },
{ q: "Listen to me", a: "Escute-me" },
{ q: "Wait here", a: "Espere aqui" },
{ q: "Come here", a: "Venha aqui" },
{ q: "I work today", a: "Eu trabalho hoje" },
{ q: "I study today", a: "Eu estudo hoje" },
{ q: "I play games", a: "Eu jogo jogos" },
{ q: "I watch movies", a: "Eu assisto filmes" },
{ q: "I have time", a: "Eu tenho tempo" },
{ q: "I have money", a: "Eu tenho dinheiro" },
{ q: "I go home", a: "Eu vou para casa" },
{ q: "I come back", a: "Eu volto" },
{ q: "Life is good", a: "A vida é boa" },
{ q: "Today is nice", a: "Hoje está bom" },
{ q: "How are you", a: "Como você está" },
{ q: "I am fine", a: "Eu estou bem" },
{ q: "What is your name", a: "Qual é seu nome" },
{ q: "My name is John", a: "Meu nome é John" },
{ q: "Nice to meet you", a: "Prazer em conhecer você" },
{ q: "Where are you", a: "Onde você está" },
{ q: "I am here", a: "Eu estou aqui" },
{ q: "Where are you from", a: "De onde você é" },
{ q: "I am from Brazil", a: "Eu sou do Brasil" },
{ q: "What are you doing", a: "O que você está fazendo" },
{ q: "I am working", a: "Eu estou trabalhando" },
{ q: "I am studying", a: "Eu estou estudando" },
{ q: "I am resting", a: "Eu estou descansando" },
{ q: "Speak slowly", a: "Fale devagar" },
{ q: "Speak up", a: "Fale mais alto" },
{ q: "Speak to me", a: "Fale comigo" },
{ q: "Speak the truth", a: "Fale a verdade" },
{ q: "Speak English", a: "Fale inglês" },
{ q: "Can you speak?", a: "Você pode falar?" },
{ q: "Don't speak", a: "Não fale" },
{ q: "Speak clearly", a: "Fale claramente" },
{ q: "Speak now", a: "Fale agora" },
{ q: "I can't speak", a: "Eu não consigo falar" },
{ q: "Do you understand", a: "Você entende" },
{ q: "I understand", a: "Eu entendo" },
{ q: "I do not understand", a: "Eu não entendo" },
{ q: "Right now", a: "Agora mesmo" },
{ q: "Just now", a: "Agora há pouco" },
{ q: "Now or never", a: "Agora ou nunca" },
{ q: "From now on", a: "A partir de agora" },
{ q: "Now and then", a: "De vez em quando" },
{ q: "For now", a: "Por enquanto" },
{ q: "Now I understand", a: "Agora eu entendo" },
{ q: "Start now", a: "Comece agora" },
{ q: "Not now", a: "Agora não" },
{ q: "Hurry now", a: "Depressa agora" },
{ q: "Can you help me", a: "Você pode me ajudar" },
{ q: "I need help", a: "Eu preciso de ajuda" },
{ q: "What time is it", a: "Que horas são" },
{ q: "It is late", a: "Está tarde" },
{ q: "It is early", a: "Está cedo" },
{ q: "I am hungry", a: "Eu estou com fome" },
{ q: "I am thirsty", a: "Eu estou com sede" },
{ q: "Let us go", a: "Vamos" },
{ q: "Wait a moment", a: "Espere um momento" },
{ q: "Just a second", a: "Só um segundo" },
{ q: "No problem", a: "Sem problema" },
{ q: "That is fine", a: "Tudo bem" },
{ q: "I agree", a: "Eu concordo" },
{ q: "I disagree", a: "Eu discordo" },
{ q: "What do you want", a: "O que você quer" },
{ q: "I want water", a: "Eu quero água" },
{ q: "I want food", a: "Eu quero comida" },
{ q: "Where is the bathroom", a: "Onde é o banheiro" },
{ q: "Where is the place", a: "Onde é o lugar" },
{ q: "Come here", a: "Venha aqui" },
{ q: "Go there", a: "Vá lá" },
{ q: "I will go", a: "Eu vou" },
{ q: "I will stay", a: "Eu vou ficar" },
{ q: "I like this", a: "Eu gosto disso" },
{ q: "I do not like this", a: "Eu não gosto disso" },
{ q: "It is good", a: "É bom" },
{ q: "It is bad", a: "É ruim" },
{ q: "This is a book", a: "Isso é um livro" },
{ q: "I have a car", a: "Eu tenho um carro" },
{ q: "She is a teacher", a: "Ela é uma professora" },
{ q: "He has a dog", a: "Ele tem um cachorro" },
{ q: "This is an apple", a: "Isso é uma maçã" },
{ q: "I saw an animal", a: "Eu vi um animal" },
{ q: "I have one book", a: "Eu tenho um livro" },
{ q: "She has two cats", a: "Ela tem dois gatos" },
{ q: "There are three apples", a: "Há três maçãs" },
{ q: "He bought four cars", a: "Ele comprou quatro carros" },
{ q: "We see five birds", a: "Nós vemos cinco pássaros" },
{ q: "She ate an orange", a: "Ela comeu uma laranja" },
{ q: "He is an engineer", a: "Ele é um engenheiro" },
{ q: "The book is on the table", a: "O livro está na mesa" },
{ q: "The car is blue", a: "O carro é azul" },
{ q: "The dog is in the house", a: "O cachorro está na casa" },
{ q: "I like the movie", a: "Eu gosto do filme" },
{ q: "She has a cat in the house", a: "Ela tem um gato na casa" },
{ q: "He bought a new phone", a: "Ele comprou um celular novo" },
{ q: "This is the school", a: "Esta é a escola" },
{ q: "I see a bird in the tree", a: "Eu vejo um pássaro na árvore" },
{ q: "She is reading a book", a: "Ela está lendo um livro" },
{ q: "The sun is hot", a: "O sol está quente" },
{ q: "He found a key", a: "Ele encontrou uma chave" },
{ q: "The door is open", a: "A porta está aberta" },
{ q: "See you later", a: "Até mais" },
{ q: "Take care", a: "Se cuida" },
{ q: "I try every day", a: "Eu tento todos os dias" },
{ q: "She tries again", a: "Ela tenta novamente" },
{ q: "He tries to learn", a: "Ele tenta aprender" },
{ q: "They try together", a: "Eles tentam juntos" },
{ q: "We try to win", a: "Nós tentamos vencer" },
{ q: "I try to understand", a: "Eu tento entender" },
{ q: "She tries to help", a: "Ela tenta ajudar" },
{ q: "He tries every time", a: "Ele tenta toda vez" },
{ q: "They try to fix it", a: "Eles tentam consertar isso" },
{ q: "We try again", a: "Nós tentamos novamente" },
{ q: "The grass is green", a: "A grama é verde" },
{ q: "The sun is yellow", a: "O sol é amarelo" },
{ q: "The car is red", a: "O carro é vermelho" },
{ q: "The night is black", a: "A noite é preta" },
{ q: "The snow is white", a: "A neve é branca" },
{ q: "The shirt is blue", a: "A camisa é azul" },
{ q: "The apple is red", a: "A maçã é vermelha" },
{ q: "The leaf is green", a: "A folha é verde" },
{ q: "The banana is yellow", a: "A banana é amarela" },
{ q: "The dog is brown", a: "O cachorro é marrom" },
{ q: "The cat is black", a: "O gato é preto" },
{ q: "The house is white", a: "A casa é branca" },
{ q: "The flower is pink", a: "A flor é rosa" },
{ q: "The ocean is blue", a: "O oceano é azul" },
{ q: "The wall is gray", a: "A parede é cinza" },
{ q: "The car is black", a: "O carro é preto" },
{ q: "The bird is yellow", a: "O pássaro é amarelo" },
{ q: "The dress is red", a: "O vestido é vermelho" },
{ q: "The hat is green", a: "O chapéu é verde" },
{ q: "She uses the phone", a: "Ela usa o celular" },
{ q: "He works on the computer", a: "Ele usa o computador" },
{ q: "We sit at the table", a: "Nós usamos a mesa" },
{ q: "They sit on the chair", a: "Eles usam a cadeira" },
{ q: "She reads the book", a: "Ela usa o livro" },
{ q: "He types on the keyboard", a: "Ele usa o teclado" },
{ q: "We move the mouse", a: "Nós usamos o mouse" },
{ q: "They look at the screen", a: "Eles usam a tela" },
{ q: "She writes with a pen", a: "Ela usa a caneta" },
{ q: "He studies with the notebook", a: "Ele usa o caderno" },
{ q: "We carry a bag", a: "Nós usamos a bolsa/mochila" },
{ q: "They open the door", a: "Eles usam a porta" },
{ q: "She turns on the lamp", a: "Ela usa a lâmpada" },
{ q: "He opens the window", a: "Ele usa a janela" },
{ q: "We drink from a bottle", a: "Nós usamos a garrafa" },
{ q: "They drink from a cup", a: "Eles usam o copo" },
{ q: "She eats with a spoon", a: "Ela usa a colher" },
{ q: "He eats with a fork", a: "Ele usa o garfo" },
{ q: "We cut with a knife", a: "Nós usamos a faca" },
{ q: "They carry a key", a: "Eles usam a chave" },
{ q: "She can use the phone", a: "Ela pode usar o celular" },
{ q: "He can work on the computer", a: "Ele pode usar o computador" },
{ q: "We can sit at the table", a: "Nós podemos usar a mesa" },
{ q: "They can sit on the chair", a: "Eles podem usar a cadeira" },
{ q: "She should read the book", a: "Ela deve ler o livro" },
{ q: "He should study with the notebook", a: "Ele deve usar o caderno" },
{ q: "We must open the door", a: "Nós devemos usar a porta" },
{ q: "They must turn on the lamp", a: "Eles devem usar a lâmpada" },
{ q: "She may use the pen", a: "Ela pode usar a caneta" },
{ q: "He may open the window", a: "Ele pode usar a janela" },
{ q: "We can drink from a bottle", a: "Nós podemos usar a garrafa" },
{ q: "They can drink from a cup", a: "Eles podem usar o copo" },
{ q: "She should eat with a spoon", a: "Ela deve usar a colher" },
{ q: "He should eat with a fork", a: "Ele deve usar o garfo" },
{ q: "We must cut with a knife", a: "Nós devemos usar a faca" },
{ q: "They must carry a key", a: "Eles devem usar a chave" },
{ q: "She can turn on the lamp", a: "Ela pode usar a lâmpada" },
{ q: "He can write with a pen", a: "Ele pode usar a caneta" },
{ q: "We should look at the screen", a: "Nós devemos usar a tela" },
{ q: "They may carry a bag", a: "Eles podem usar a bolsa/mochila" },
{ q: "The cat is between the boxes", a: "O gato está entre as caixas" },
{ q: "I am between my friends", a: "Eu estou entre meus amigos" },
{ q: "The book is between the laptop and the lamp", a: "O livro está entre o notebook e a luminária" },
{ q: "The bank is between the school and the park", a: "O banco está entre a escola e o parque" },
{ q: "She sits between her parents", a: "Ela senta entre seus pais" },
{ q: "The ball is between the players", a: "A bola está entre os jogadores" },
{ q: "He stands between the cars", a: "Ele está entre os carros" },
{ q: "The river is between the mountains", a: "O rio está entre as montanhas" },
{ q: "There is a secret between us", a: "Há um segredo entre nós" },
{ q: "The store is between two houses", a: "A loja está entre duas casas" },
{ q: "I am between you and the door", a: "Eu estou entre você e a porta" },
{ q: "The phone is between the keys", a: "O telefone está entre as chaves" },
{ q: "The sun is between the clouds", a: "O sol está entre as nuvens" },
{ q: "The line is between the words", a: "A linha está entre as palavras" },
{ q: "The chair is between the tables", a: "A cadeira está entre as mesas" },
{ q: "Put the paper between the pages", a: "Coloque o papel entre as páginas" },
{ q: "The city is between the forest and the sea", a: "A cidade está entre a floresta e o mar" },
{ q: "She is between five and six", a: "Ela tem entre cinco e seis anos" },
{ q: "Meet me between eight and nine", a: "Encontre-me entre as oito e as nove" },
{ q: "Choose between the two colors", a: "Escolha entre as duas cores" }

];


VOCAB_GRAMMAR = [
{ q: "He runs", a: "Ele corre", note: "Presente simples (He She It + S)" },
{ q: "She works", a: "Ela trabalha", note: "Presente simples (He She It + S)" },
{ q: "It rains", a: "Chove", note: "Presente simples (He She It + S)" },

{ q: "I run", a: "Eu corro", note: "Presente simples" },
{ q: "You work", a: "Você trabalha", note: "Presente simples" },

{ q: "I am eating", a: "Eu estou comendo", note: "Present Continuous (am + ing)" },
{ q: "He is running", a: "Ele está correndo", note: "Present Continuous (is + ing)" },
{ q: "They are playing", a: "Eles estão jogando", note: "Present Continuous (are + ing)" },

{ q: "I will go", a: "Eu irei", note: "Futuro (will + verbo)" },
{ q: "She will come", a: "Ela virá", note: "Futuro (will + verbo)" },
{ q: "We will win", a: "Nós venceremos", note: "Futuro (will + verbo)" },

{ q: "I went", a: "Eu fui", note: "Passado simples" },
{ q: "She ate", a: "Ela comeu", note: "Passado simples" },
{ q: "They saw", a: "Eles viram", note: "Passado simples" },

{ q: "I have eaten", a: "Eu comi", note: "Present Perfect (have + particípio)" },
{ q: "She has gone", a: "Ela foi", note: "Present Perfect (has + particípio)" },

{ q: "I am happy", a: "Eu estou feliz", note: "Verbo to be" },
{ q: "He is tired", a: "Ele está cansado", note: "Verbo to be" },
{ q: "They are ready", a: "Eles estão prontos", note: "Verbo to be" },

{ q: "I am not ready", a: "Eu não estou pronto", note: "Negação com to be" },
{ q: "He is not here", a: "Ele não está aqui", note: "Negação com to be" },

{ q: "Do you work", a: "Você trabalha", note: "Pergunta com do" },
{ q: "Do they play", a: "Eles jogam", note: "Pergunta com do" },

{ q: "Does he work", a: "Ele trabalha", note: "Pergunta com does" },
{ q: "Does she like", a: "Ela gosta", note: "Pergunta com does" },

{ q: "I do not know", a: "Eu não sei", note: "Negação com do" },
{ q: "He does not like", a: "Ele não gosta", note: "Negação com does" },

{ q: "Can you help", a: "Você pode ajudar", note: "Modal can" },
{ q: "I can do", a: "Eu posso fazer", note: "Modal can" },
{ q: "He can go", a: "Ele pode ir", note: "Modal can" },

{ q: "I cannot go", a: "Eu não posso ir", note: "Negação com can" },

{ q: "I want to eat", a: "Eu quero comer", note: "Want to + verbo" },
{ q: "I need to go", a: "Eu preciso ir", note: "Need to + verbo" },

{ q: "I like to play", a: "Eu gosto de jogar", note: "Like to + verbo" },
{ q: "I like playing", a: "Eu gosto de jogar", note: "Like + ing" },

{ q: "I am going to eat", a: "Eu vou comer", note: "Going to futuro" },
{ q: "She is going to travel", a: "Ela vai viajar", note: "Going to futuro" },

{ q: "There is a car", a: "Há um carro", note: "There is singular" },
{ q: "There are cars", a: "Há carros", note: "There are plural" },

{ q: "This is good", a: "Isso é bom", note: "This singular" },
{ q: "These are good", a: "Esses são bons", note: "These plural" },

{ q: "That is bad", a: "Aquilo é ruim", note: "That singular" },
{ q: "Those are bad", a: "Aqueles são ruins", note: "Those plural" },

{ q: "My name is John", a: "Meu nome é John", note: "Possessivo my" },
{ q: "Your car is fast", a: "Seu carro é rápido", note: "Possessivo your" },

{ q: "I have a car", a: "Eu tenho um carro", note: "Have posse" },
{ q: "She has a house", a: "Ela tem uma casa", note: "Has terceira pessoa" },
{ q: "I am", a: "Eu sou", note: "Verbo to be" },
{ q: "You are", a: "Você é", note: "Verbo to be" },
{ q: "He is", a: "Ele é", note: "Verbo to be" },
{ q: "twenty-one", a: "vinte e um", note: "Número composto (20 + 1)" },
{ q: "She is", a: "Ela é", note: "Verbo to be" },
{ q: "We are", a: "Nós somos", note: "Verbo to be" },
{ q: "They are", a: "Eles são", note: "Verbo to be" },
{ q: "I have twenty-one books", a: "Eu tenho vinte e um livros", note: "Quantidade usando número composto" },
{ q: "She has thirty-four friends", a: "Ela tem trinta e quatro amigos", note: "Quantidade usando número composto" },
{ q: "There are forty-five students", a: "Há quarenta e cinco alunos", note: "Quantidade em grupo" },
{ q: "He bought fifty-six apples", a: "Ele comprou cinquenta e seis maçãs", note: "Compras com números compostos" },
{ q: "We saw sixty-seven birds", a: "Nós vimos sessenta e sete pássaros", note: "Quantidade observada" },
{ q: "They have seventy-eight cars", a: "Eles têm setenta e oito carros", note: "Possessão em grande quantidade" },
{ q: "She read eighty-nine pages", a: "Ela leu oitenta e nove páginas", note: "Leitura com número alto" },
{ q: "I met ninety-one people", a: "Eu conheci noventa e um pessoas", note: "Encontros com pessoas" },
{ q: "He saw forty-two stars", a: "Ele viu quarenta e dois estrelas", note: "Observação de objetos" },
{ q: "We ate fifty-three sandwiches", a: "Nós comemos cinquenta e três sanduíches", note: "Consumo com número composto" },
{ q: "I am not", a: "Eu não sou", note: "Negação com to be" },
{ q: "He is not", a: "Ele não é", note: "Negação com to be" },

{ q: "Are you", a: "Você é", note: "Pergunta com to be" },
{ q: "Is he", a: "Ele é", note: "Pergunta com to be" },

{ q: "I have", a: "Eu tenho", note: "Have posse" },
{ q: "She has", a: "Ela tem", note: "Has terceira pessoa" },

{ q: "I do", a: "Eu faço", note: "Verbo base" },
{ q: "He does", a: "Ele faz", note: "Does terceira pessoa" },

{ q: "I do not", a: "Eu não faço", note: "Negação com do" },
{ q: "He does not", a: "Ele não faz", note: "Negação com does" },

{ q: "Do you", a: "Você faz", note: "Pergunta com do" },
{ q: "Does he", a: "Ele faz", note: "Pergunta com does" },

{ q: "I can", a: "Eu posso", note: "Modal can" },
{ q: "You can", a: "Você pode", note: "Modal can" },
{ q: "I cannot", a: "Eu não posso", note: "Negação com can" },

{ q: "I will", a: "Eu vou", note: "Futuro com will" },
{ q: "He will", a: "Ele vai", note: "Futuro com will" },

{ q: "I will not", a: "Eu não vou", note: "Negação com will" },

{ q: "I am doing", a: "Eu estou fazendo", note: "Present Continuous" },
{ q: "He is going", a: "Ele está indo", note: "Present Continuous" },
{ q: "They are working", a: "Eles estão trabalhando", note: "Present Continuous" },

{ q: "I go", a: "Eu vou", note: "Presente simples" },
{ q: "He goes", a: "Ele vai", note: "Presente simples (S)" },

{ q: "I went", a: "Eu fui", note: "Passado simples" },
{ q: "He went", a: "Ele foi", note: "Passado simples" },

{ q: "I want", a: "Eu quero", note: "Verbo comum" },
{ q: "I need", a: "Eu preciso", note: "Verbo comum" },
{ q: "I like", a: "Eu gosto", note: "Verbo comum" },

{ q: "I want to go", a: "Eu quero ir", note: "Want to + verbo" },
{ q: "I need to work", a: "Eu preciso trabalhar", note: "Need to + verbo" },

{ q: "I am going to go", a: "Eu vou ir", note: "Going to futuro" },

{ q: "There is", a: "Há", note: "Existência singular" },
{ q: "There are", a: "Há", note: "Existência plural" },

{ q: "This is", a: "Isso é", note: "This singular" },
{ q: "That is", a: "Aquilo é", note: "That singular" },

{ q: "These are", a: "Esses são", note: "These plural" },
{ q: "Those are", a: "Aqueles são", note: "Those plural" },
{ q: "He tries", a: "Ele tenta", note: "Presente simples (He/She/It + ies)" },
{ q: "She tries", a: "Ela tenta", note: "Presente simples (He/She/It + ies)" },
{ q: "It tries", a: "Isso tenta", note: "Presente simples (He/She/It + ies)" },
{ q: "I try", a: "Eu tento", note: "Presente simples (I/You/We/They sem alteração)" },
{ q: "They try", a: "Eles tentam", note: "Presente simples (plural sem alteração)" },
{ q: "We try", a: "Nós tentamos", note: "Presente simples (plural sem alteração)" },
{ q: "You try", a: "Você tenta", note: "Presente simples (sem alteração)" },
{ q: "He tries to learn", a: "Ele tenta aprender", note: "He + tries (verbo termina em Y → IES)" },
{ q: "She tries again", a: "Ela tenta novamente", note: "He/She/It + ies no presente" },
{ q: "It tries to move", a: "Isso tenta se mover", note: "He/She/It + ies (regra do Y)" },
{ q: "In", a: "Em", note: "Preposição" },
{ q: "On", a: "Em cima", note: "Preposição" },
{ q: "At", a: "Em", note: "Preposição" },
{ q: "Goodbye", a: "Adeus", note: "Saudação de despedida" },
{ q: "Commitment", a: "Compromisso", note: "Substantivo" },
{ q: "I am", a: "Eu sou ou estou", note: "Usado com I no presente" },
{ q: "You are", a: "Você é ou está", note: "Usado com you no presente" },
{ q: "He is", a: "Ele é ou está", note: "Usado com he no presente" },
{ q: "She is", a: "Ela é ou está", note: "Usado com she no presente" },
{ q: "It is", a: "Isso é ou está", note: "Usado com it no presente" },
{ q: "We are", a: "Nós somos ou estamos", note: "Usado com we no presente" },
{ q: "They are", a: "Eles são ou estão", note: "Usado com they no presente" },
{ q: "I am not", a: "Eu não sou ou estou", note: "Negação com I" },
{ q: "You are not", a: "Você não é ou está", note: "Negação com you" },
{ q: "He is not", a: "Ele não é ou está", note: "Negação com he" },
{ q: "She is not", a: "Ela não é ou está", note: "Negação com she" },
{ q: "I miss you", a: "Sinto sua falta", note: "Expressão de saudade" },
{q: "Take care", a: "Se cuida", note: "Expressão de despedida carinhosa" },
{ q: "I love you", a: "Eu te amo", note: "Expressão de amor" },
{ q: "See you later", a: "Até mais tarde", note: "Despedida informal" },
{ q: "See you soon", a: "Até logo", note: "Despedida com expectativa de reencontro" },
{ q: "Good luck", a: "Boa sorte", note: "Desejo positivo" },
{ q: "Stay safe", a: "Fique seguro", note: "Cuidado e proteção" },
{ q: "I care about you", a: "Eu me importo com você", note: "Expressão de afeto" },
{ q: "Miss you too", a: "Também sinto sua falta", note: "Resposta de saudade" },
{ q: "I miss you too", a: "Eu também sinto sua falta", note: "Resposta de saudade" },
{ q: "Too late", a: "Tarde demais", note: "Expressão de tempo" },
{ q: "Me too", a: "Eu também", note: "Resposta de concordância" },
{ q: "Too much", a: "Demais", note: "Quantidade excessiva" },
{ q: "It is not", a: "Isso não é ou está", note: "Negação com it" },
{ q: "Too much", a: "Demais", note: "Quantidade excessiva" },
{ q: "Much better", a: "Muito melhor", note: "Comparação positiva" },
{ q: "Much love", a: "Muito amor", note: "Expressão de carinho" },
{ q: "How much", a: "Quanto / quanta", note: "Pergunta sobre quantidade" },
{ q: "So much", a: "Tanto / muito", note: "Intensidade" },
{ q: "Too late", a: "Tarde demais", note: "Algo aconteceu depois do tempo ideal" },
{ q: "Late at night", a: "Tarde da noite", note: "Período da noite" },
{ q: "Running late", a: "Atrasado", note: "Quando alguém está fora do horário" },
{ q: "Better late than never", a: "Antes tarde do que nunca", note: "Expressão idiomática" },
{ q: "Stay up late", a: "Ficar acordado até tarde", note: "Ação de não dormir cedo" },
{ q: "Wake up", a: "Acordar", note: "Sair do sono" },
{ q: "Get up", a: "Levantar", note: "Sair da cama" },
{ q: "Stand up", a: "Ficar de pé", note: "Ação física" },
{ q: "Grow up", a: "Crescer", note: "Tornar-se adulto" },
{ q: "Give up", a: "Desistir", note: "Parar de tentar" },
{ q: "Speak up", a: "Falar mais alto / se pronunciar", note: "Expressar opinião" },
{ q: "Shut up", a: "Cala a boca", note: "Expressão informal (rude)" },
{ q: "Cheer up", a: "Animar-se", note: "Ficar mais feliz" },
{ q: "Turn up", a: "Aumentar / aparecer", note: "Depende do contexto" },
{ q: "Look up", a: "Procurar / olhar para cima", note: "Buscar informação ou direção" },
{ q: "Promise", a: "Promessa", note: "Substantivo" },
{ q: "Trust", a: "Confiança", note: "Substantivo" },
{ q: "Loyalty", a: "Lealdade", note: "Substantivo" },
{ q: "Respect", a: "Respeito", note: "Substantivo" },
{ q: "Farewell", a: "Despedida", note: "Saudação de partida" },
{ q: "See you", a: "Até logo", note: "Expressão informal de despedida" },
{ q: "Goodnight", a: "Boa noite", note: "Saudação de despedida noturna" },
{ q: "Hello", a: "Olá", note: "Saudação" },
{ q: "Friendship", a: "Amizade", note: "Substantivo" },
{ q: "Gratitude", a: "Gratidão", note: "Substantivo" },
{ q: "We are not", a: "Nós não somos ou estamos", note: "Negação com we" },
{ q: "They are not", a: "Eles não são ou estão", note: "Negação com they" },
{ q: "Am I", a: "Eu sou ou estou", note: "Pergunta com I" },
{ q: "Are you", a: "Você é ou está", note: "Pergunta com you" },
{ q: "Is he", a: "Ele é ou está", note: "Pergunta com he" },
{ q: "Is she", a: "Ela é ou está", note: "Pergunta com she" },
{ q: "Is it", a: "Isso é ou está", note: "Pergunta com it" },
{ q: "Are we", a: "Nós somos ou estamos", note: "Pergunta com we" },
{ q: "Are they", a: "Eles são ou estão", note: "Pergunta com they" },
{ q: "I am happy", a: "Eu sou feliz", note: "Verbo TO BE: am é usado apenas com I" },
{ q: "Are you ready", a: "Você está pronto", note: "Em perguntas o Verbo TO BE vem antes do sujeito" },
{ q: "He is not sad", a: "Ele não está triste", note: "Negação: usamos NOT após o verbo is/am/are" },
{ q: "I was there", a: "Eu estava lá", note: "Passado: WAS é o passado de AM e IS" },
{ q: "They were fast", a: "Eles eram rápidos", note: "Passado: WERE é o passado de ARE" },

// --- PRESENTE SIMPLES (Regra do S) ---
{ q: "She likes music", a: "Ela gosta de música", note: "3ª Pessoa (He/She/It): adiciona S ao verbo no presente" },
{ q: "It works well", a: "Funciona bem", note: "3ª Pessoa: mesmo para objetos (It), o verbo ganha S" },
{ q: "He cries a lot", a: "Ele chora muito", note: "Verbos em Y precedido de consoante mudam para IES" },
{ q: "She watches TV", a: "Ela assiste TV", note: "Verbos terminados em CH/SH/X/O ganham ES na 3ª pessoa" },
{ q: "Do you dance", a: "Você dança", note: "Perguntas: usamos o auxiliar DO para I/You/We/They" },
{ q: "Does he cook", a: "Ele cozinha", note: "Perguntas: usamos DOES para He/She/It (o verbo perde o S)" },
{ q: "I don't care", a: "Eu não me importo", note: "Negação: DON'T é a contração de DO NOT" },
{ q: "She doesn't sleep", a: "Ela não dorme", note: "Negação: DOESN'T é usado para He/She/It" },

// --- CONTINUOUS (ING) ---
{ q: "We are studying", a: "Nós estamos estudando", note: "Present Continuous: Verbo To Be + ING" },
{ q: "I am reading", a: "Eu estou lendo", note: "ING no final do verbo equivale ao nosso 'ando', 'endo', 'indo'" },
{ q: "She is working", a: "Ela está trabalhando", note: "Present Continuous: ação acontecendo agora" },
{ q: "They are playing", a: "Eles estão jogando", note: "Present Continuous: ação em andamento" },
{ q: "He is eating", a: "Ele está comendo", note: "ING indica ação contínua no presente" },
{ q: "We are learning", a: "Nós estamos aprendendo", note: "Ação acontecendo no momento" },
{ q: "I am studying English", a: "Eu estou estudando inglês", note: "Verbo To Be + ING para ações em progresso" },
{ q: "She is talking", a: "Ela está falando", note: "Ação contínua no presente" },
{ q: "They are watching TV", a: "Eles estão assistindo TV", note: "Ação em andamento agora" },
{ q: "He is sleeping", a: "Ele está dormindo", note: "Estado contínuo no presente" },
{ q: "We are working together", a: "Nós estamos trabalhando juntos", note: "Ação simultânea" },
{ q: "I am writing a message", a: "Eu estou escrevendo uma mensagem", note: "Ação acontecendo agora com ING" },

// --- MODAIS (Can, Should, Must, Could) ---
{ q: "I can swim", a: "Eu posso nadar", note: "CAN: indica habilidade. Não use 'to' depois de can" },
{ q: "You should go", a: "Você deveria ir", note: "SHOULD: usado para dar conselhos ou sugestões" },
{ q: "We must wait", a: "Nós devemos esperar", note: "MUST: indica obrigação ou necessidade forte" },
{ q: "He could play", a: "Ele podia jogar", note: "COULD: é o passado de CAN (podia/conseguia)" },
{ q: "I can't hear", a: "Eu não consigo ouvir", note: "CAN'T: contração de CAN NOT" },

// --- FUTURO (Will & Going To) ---
{ q: "They will arrive", a: "Eles chegarão", note: "WILL: indica um futuro incerto ou decidido na hora" },
{ q: "It will rain", a: "Vai chover", note: "WILL: também usado para previsões do tempo" },
{ q: "I'm going to eat", a: "Eu vou comer", note: "GOING TO: futuro para planos já decididos" },

// --- PASSADO SIMPLES ---
{ q: "I loved it", a: "Eu amei isso", note: "Passado Regular: basta adicionar ED ao final do verbo" },
{ q: "He said yes", a: "Ele disse sim", note: "Irregular: SAID é o passado de SAY" },
{ q: "She saw me", a: "Ela me viu", note: "Irregular: SAW é o passado de SEE" },
{ q: "We went away", a: "Nós fomos embora", note: "Irregular: WENT é o passado de GO" },
{ q: "Did you go", a: "Você foi", note: "Pergunta no passado: usamos DID (o verbo volta ao normal)" },
{ q: "I didn't stay", a: "Eu não fiquei", note: "Negação no passado: DIDN'T + verbo no normal" },


// --- POSSESSIVOS & PRONOMES ---
{ q: "This is my book", a: "Este é meu livro", note: "MY: possessivo que vem antes do objeto" },
{ q: "That is her car", a: "Aquele é o carro dela", note: "HER: possessivo para 'dela'" },
{ q: "Look at him", a: "Olhe para ele", note: "HIM: usado como objeto da frase (quem recebe a ação)" },
{ q: "Tell me", a: "Diga-me", note: "ME: pronome objeto para 'eu/mim'" },

// --- PREPOSIÇÕES & QUANTIDADE ---
{ q: "In the box", a: "Na caixa", note: "IN: usado para dentro de algo ou lugares fechados" },
{ q: "On the table", a: "Em cima da mesa", note: "ON: usado para superfícies ou dias da semana" },
{ q: "At night", a: "À noite", note: "AT: preposição para horas ou períodos específicos" },
{ q: "An apple", a: "Uma maçã", note: "AN: usado antes de palavras que começam com som de vogal" },
{ q: "A dog", a: "Um cachorro", note: "A: usado antes de palavras com som de consoante" },
{ q: "Some water", a: "Alguma água", note: "SOME: usado para quantidades indefinidas (algum/um pouco)" },

// --- COMPARATIVOS ---
{ q: "Bigger than", a: "Maior do que", note: "Comparativo: adjetivos curtos ganham ER no final" },
{ q: "More beautiful", a: "Mais bonito", note: "Comparativo: adjetivos longos usam MORE antes" },
{ q: "Better than", a: "Melhor que", note: "Irregular: GOOD vira BETTER no comparativo" },

// --- PRESENT PERFECT (Intermediário) ---
{ q: "I have done", a: "Eu fiz", note: "Present Perfect: Have + Particípio (ação que reflete no presente)" },
{ q: "She has eaten", a: "Ela comeu", note: "Present Perfect: usa-se HAS para He/She/It" },

// --- OUTROS ---
{ q: "There is a man", a: "Há um homem", note: "THERE IS: existe/há para uma única coisa" },
{ q: "There are kids", a: "Há crianças", note: "THERE ARE: existe/há para duas ou mais coisas" },
{ q: "I always study", a: "Eu sempre estudo", note: "Advérbios de frequência vêm antes do verbo principal" },
{ q: "Too hot", a: "Quente demais", note: "TOO: antes de um adjetivo significa excesso (demais)" },
{ q: "Not enough", a: "Não o suficiente", note: "ENOUGH: vem depois de adjetivos ou antes de substantivos" },
{ q: "I used to play", a: "Eu costumava jogar", note: "USED TO: indica um hábito que você tinha no passado" },
{ q: "She is at home", a: "Ela está em casa", note: "Uso de 'at' para lugar específico" },
{ q: "The book is on the table", a: "O livro está na mesa", note: "Uso de 'on' para superfície" },
{ q: "The cat is under the chair", a: "O gato está embaixo da cadeira", note: "Uso de 'under' para posição abaixo" },
{ q: "He is in the room", a: "Ele está no quarto", note: "Uso de 'in' para dentro de algo" },
{ q: "She is next to me", a: "Ela está ao meu lado", note: "Uso de 'next to' para proximidade" },
{ q: "The car is in front of the house", a: "O carro está na frente da casa", note: "Uso de 'in front of' para posição frontal" },
{ q: "The dog is behind the door", a: "O cachorro está atrás da porta", note: "Uso de 'behind' para posição atrás" },
{ q: "He goes to school", a: "Ele vai para a escola", note: "Uso de 'to' para destino" },
{ q: "She comes from Brazil", a: "Ela vem do Brasil", note: "Uso de 'from' para origem" },
{ q: "I am with my friend", a: "Eu estou com meu amigo", note: "Uso de 'with' para companhia" },
{ q: "He did it for you", a: "Ele fez isso por você", note: "Uso de 'for' para finalidade" },
{ q: "This is about you", a: "Isso é sobre você", note: "Uso de 'about' para assunto" },
{ q: "A piece of cake", a: "Um pedaço de bolo", note: "Uso de 'of' para relação/posse" },
{ q: "The letter is by the door", a: "A carta está perto da porta", note: "Uso de 'by' para proximidade" },
{ q: "We talk after work", a: "Nós conversamos depois do trabalho", note: "Uso de 'after' para tempo" },
{ q: "Finish this before dinner", a: "Termine isso antes do jantar", note: "Uso de 'before' para tempo" },
{ q: "The plane flies above the clouds", a: "O avião voa acima das nuvens", note: "Uso de 'above' para posição acima" },
{ q: "The temperature is below zero", a: "A temperatura está abaixo de zero", note: "Uso de 'below' para nível inferior" },
{ q: "She sits between two friends", a: "Ela senta entre dois amigos", note: "Uso de 'between' para dois elementos" },
{ q: "He walked among the people", a: "Ele caminhou entre as pessoas", note: "Uso de 'among' para vários elementos" },
{ q: "The car is between the trucks", a: "O carro está entre os caminhões", note: "Between: usado para algo no meio de dois elementos" },
{ q: "I sit between John and Mary", a: "Eu sento entre John e Mary", note: "Use between para indicar posição entre duas pessoas específicas" },
{ q: "The phone is between the keys", a: "O telefone está entre as chaves", note: "Between refere-se ao espaço que separa dois objetos" },
{ q: "Lunch is between one and two", a: "O almoço é entre uma e duas", note: "Between também é usado para intervalos de tempo" },
{ q: "The house is between two trees", a: "A casa está entre duas árvores", note: "Indica localização física centralizada" },
{ q: "Choose between red and blue", a: "Escolha entre vermelho e azul", note: "Use between ao escolher entre duas opções" },
{ q: "The city is between the mountains", a: "A cidade está entre as montanhas", note: "Montanhas (duas cadeias ou picos) pedem o uso de between" },
{ q: "A secret between you and me", a: "Um segredo entre você e eu", note: "Expressão comum para algo compartilhado por apenas dois" },
{ q: "The paper is between the pages", a: "O papel está entre as páginas", note: "Refere-se ao espaço entre a página anterior e a próxima" },
{ q: "The ball is between his feet", a: "A bola está entre os pés dele", note: "Entre dois membros do corpo usa-se between" },
{ q: "Monday is between Sunday and Tuesday", a: "Segunda é entre domingo e terça", note: "Sequenciamento de dias com between" },
{ q: "The bank is between the school and the mall", a: "O banco é entre a escola e o shopping", note: "Usado para direções e pontos de referência" },
{ q: "There is a gap between the doors", a: "Há um espaço entre as portas", note: "Indica frestas ou vãos entre dois pontos" },
{ q: "The child is between her parents", a: "A criança está entre seus pais", note: "Posição física entre duas pessoas" },
{ q: "I am between jobs", a: "Estou entre empregos", note: "Expressão que significa estar temporariamente desempregado" },
{ q: "The link between the two events", a: "A ligação entre os dois eventos", note: "Conexão lógica ou abstrata entre dois pontos" },
{ q: "The distance between London and Paris", a: "A distância entre Londres e Paris", note: "Cálculo de espaço entre dois locais" },
{ q: "He stands between the two cars", a: "Ele está entre os dois carros", note: "Localização estática entre objetos" },
{ q: "Difference between right and wrong", a: "Diferença entre certo e errado", note: "Comparação de dois conceitos opostos" },
{ q: "The space between the lines", a: "O espaço entre as linhas", note: "Refere-se ao intervalo entre duas marcações" }
];


VOCAB_FORM_SENTENCE = [
{ q: "Complete: I ___ to school every day", target: "GO", a: "go", opts: ["go", "goes", "going"] },
{ q: "Complete: He ___ to school every day", target: "GO", a: "goes", opts: ["go", "goes", "going"] },

{ q: "Complete: I ___ to school yesterday", target: "GO", a: "went", opts: ["go", "gone", "went"] },
{ q: "Complete: She ___ a book now", target: "READ", a: "is reading", opts: ["reads", "is reading", "readed"] },

{ q: "Complete: They ___ football every Sunday", target: "PLAY", a: "play", opts: ["plays", "play", "playing"] },
{ q: "Complete: He ___ football every Sunday", target: "PLAY", a: "plays", opts: ["play", "plays", "playing"] },

{ q: "Complete: We ___ a movie last night", target: "WATCH", a: "watched", opts: ["watch", "watches", "watched"] },
{ q: "Complete: I ___ TV now", target: "WATCH", a: "am watching", opts: ["watch", "am watching", "watched"] },

{ q: "Complete: She ___ coffee every morning", target: "DRINK", a: "drinks", opts: ["drink", "drinks", "drinking"] },
{ q: "Complete: I ___ coffee now", target: "DRINK", a: "am drinking", opts: ["drink", "drank", "am drinking"] },

{ q: "Complete: They ___ lunch now", target: "EAT", a: "are eating", opts: ["eat", "eats", "are eating"] },
{ q: "Complete: He ___ lunch at noon", target: "EAT", a: "eats", opts: ["eat", "eats", "eating"] },

{ q: "Complete: I ___ home yesterday", target: "COME", a: "came", opts: ["come", "came", "comes"] },
{ q: "Complete: She ___ home now", target: "COME", a: "is coming", opts: ["comes", "is coming", "come"] },

{ q: "Complete: We ___ a game now", target: "PLAY", a: "are playing", opts: ["play", "played", "are playing"] },
{ q: "Complete: I ___ a game yesterday", target: "PLAY", a: "played", opts: ["play", "plays", "played"] },

{ q: "Complete: He ___ a car", target: "HAVE", a: "has", opts: ["have", "has", "having"] },
{ q: "Complete: I ___ a car", target: "HAVE", a: "have", opts: ["have", "has", "having"] },

{ q: "Complete: She ___ happy now", target: "BE", a: "is", opts: ["is", "are", "am"] },
{ q: "Complete: They ___ happy", target: "BE", a: "are", opts: ["is", "are", "am"] },

{ q: "Complete: I ___ tired yesterday", target: "BE", a: "was", opts: ["am", "was", "were"] },
{ q: "Complete: They ___ tired yesterday", target: "BE", a: "were", opts: ["was", "were", "are"] },
{ q: "Complete: I ___ you for your help", target: "THANK", a: "thank", opts: ["thank", "thanks", "thanking"], note: "Básico: agradecer alguém diretamente" },
{ q: "Complete: She ___ her friend every day", target: "THANK", a: "thanks", opts: ["thank", "thanks", "thanking"], note: "Presente simples 3ª pessoa (She/He/It + S)" },
{ q: "Complete: We ___ God for life", target: "THANK", a: "thank", opts: ["thank", "thanks", "thanking"], note: "Uso comum em expressões emocionais/religiosas" },
{ q: "Complete: They ___ the teacher after class", target: "THANK", a: "thank", opts: ["thank", "thanks", "thanking"], note: "Ação no passado implícito no contexto da frase" },
{ q: "Complete: He is ___ her for the gift", target: "THANK", a: "thanking", opts: ["thank", "thanks", "thanking"], note: "Present continuous (is/am/are + ing)" },
{ q: "Complete: I will ___ you later", target: "THANK", a: "thank", opts: ["thank", "thanks", "thanking"], note: "Futuro com will + verbo base" },
{ q: "Complete: She has ___ him already", target: "THANK", a: "thanked", opts: ["thank", "thanks", "thanking", "thanked"], note: "Present perfect (has/have + past participle)" },
{ q: "Complete: They ___ me before I left", target: "THANK", a: "thanked", opts: ["thank", "thanks", "thanking", "thanked"], note: "Past simple (ação concluída no passado)" },
{ q: "Complete: He ___ English", target: "STUDY", a: "studies", opts: ["study", "studies", "studying"] },
{ q: "Complete: I ___ English now", target: "STUDY", a: "am studying", opts: ["study", "studied", "am studying"] },

{ q: "Complete: We ___ music now", target: "LISTEN", a: "are listening", opts: ["listen", "listens", "are listening"] },
{ q: "Complete: She ___ music every day", target: "LISTEN", a: "listens", opts: ["listen", "listens", "listening"] },

{ q: "Complete: I ___ my friend yesterday", target: "SEE", a: "saw", opts: ["see", "seen", "saw"] },
{ q: "Complete: I ___ my friend now", target: "SEE", a: "am seeing", opts: ["see", "saw", "am seeing"] },

{ q: "Complete: He ___ fast", target: "RUN", a: "runs", opts: ["run", "runs", "running"] },
{ q: "Complete: He ___ now", target: "RUN", a: "is running", opts: ["run", "ran", "is running"] },

{ q: "Complete: I ___ help", target: "NEED", a: "need", opts: ["need", "needs", "needing"] },
{ q: "Complete: She ___ help", target: "NEED", a: "needs", opts: ["need", "needs", "needing"] },

{ q: "Complete: I ___ you", target: "LIKE", a: "like", opts: ["like", "likes", "liking"] },
{ q: "Complete: He ___ you", target: "LIKE", a: "likes", opts: ["like", "likes", "liking"] },

{ q: "Complete: I ___ work tomorrow", target: "START", a: "will start", opts: ["start", "started", "will start"] },
{ q: "Complete: She ___ soon", target: "COME", a: "will come", opts: ["comes", "came", "will come"] },

{ q: "Complete: They ___ here now", target: "STAY", a: "are staying", opts: ["stay", "stayed", "are staying"] },
{ q: "Complete: I ___ here yesterday", target: "STAY", a: "stayed", opts: ["stay", "stays", "stayed"] },
{ q: "Complete: I ___ tired", target: "BE", a: "am", opts: ["am", "is", "are"] },
{ q: "Complete: You ___ right", target: "BE", a: "are", opts: ["am", "is", "are"] },
{ q: "Complete: He ___ here", target: "BE", a: "is", opts: ["am", "is", "are"] },

{ q: "Complete: I ___ hungry", target: "BE", a: "am", opts: ["am", "is", "are"] },
{ q: "Complete: She ___ busy", target: "BE", a: "is", opts: ["am", "is", "are"] },

{ q: "Complete: I ___ coffee", target: "DRINK", a: "drink", opts: ["drink", "drinks", "drinking"] },
{ q: "Complete: He ___ coffee", target: "DRINK", a: "drinks", opts: ["drink", "drinks", "drinking"] },

{ q: "Complete: I ___ water now", target: "DRINK", a: "am drinking", opts: ["drink", "drank", "am drinking"] },

{ q: "Complete: I ___ food", target: "WANT", a: "want", opts: ["want", "wants", "wanting"] },
{ q: "Complete: She ___ food", target: "WANT", a: "wants", opts: ["want", "wants", "wanting"] },

{ q: "Complete: I ___ help", target: "NEED", a: "need", opts: ["need", "needs", "needing"] },
{ q: "Complete: He ___ help", target: "NEED", a: "needs", opts: ["need", "needs", "needing"] },

{ q: "Complete: I ___ you", target: "LIKE", a: "like", opts: ["like", "likes", "liking"] },
{ q: "Complete: She ___ you", target: "LIKE", a: "likes", opts: ["like", "likes", "liking"] },

{ q: "Complete: I ___ here", target: "STAY", a: "stay", opts: ["stay", "stays", "staying"] },
{ q: "Complete: He ___ here", target: "STAY", a: "stays", opts: ["stay", "stays", "staying"] },

{ q: "Complete: I ___ to work", target: "GO", a: "go", opts: ["go", "goes", "going"] },
{ q: "Complete: She ___ to work", target: "GO", a: "goes", opts: ["go", "goes", "going"] },

{ q: "Complete: I ___ home now", target: "GO", a: "am going", opts: ["go", "went", "am going"] },

{ q: "Complete: I ___ TV", target: "WATCH", a: "watch", opts: ["watch", "watches", "watching"] },
{ q: "Complete: He ___ TV", target: "WATCH", a: "watches", opts: ["watch", "watches", "watching"] },

{ q: "Complete: I ___ TV now", target: "WATCH", a: "am watching", opts: ["watch", "watched", "am watching"] },

{ q: "Complete: I ___ music", target: "LISTEN", a: "listen", opts: ["listen", "listens", "listening"] },
{ q: "Complete: She ___ music", target: "LISTEN", a: "listens", opts: ["listen", "listens", "listening"] },

{ q: "Complete: I ___ now", target: "WORK", a: "am working", opts: ["work", "worked", "am working"] },
{ q: "Complete: He ___ every day", target: "WORK", a: "works", opts: ["work", "works", "working"] },

{ q: "Complete: I ___ English", target: "STUDY", a: "study", opts: ["study", "studies", "studying"] },
{ q: "Complete: She ___ English", target: "STUDY", a: "studies", opts: ["study", "studies", "studying"] },

{ q: "Complete: I ___ English now", target: "STUDY", a: "am studying", opts: ["study", "studied", "am studying"] },

{ q: "Complete: I ___ you now", target: "CALL", a: "am calling", opts: ["call", "called", "am calling"] },
{ q: "Complete: He ___ you", target: "CALL", a: "calls", opts: ["call", "calls", "calling"] },

{ q: "Complete: I ___ something", target: "DO", a: "do", opts: ["do", "does", "doing"] },
{ q: "Complete: She ___ something", target: "DO", a: "does", opts: ["do", "does", "doing"] },

{ q: "Complete: I ___ it", target: "KNOW", a: "know", opts: ["know", "knows", "knowing"] },
{ q: "Complete: He ___ it", target: "KNOW", a: "knows", opts: ["know", "knows", "knowing"] },
{ q: "Complete: This is ___ book", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: She has ___ apple", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: ___ sun is hot", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: I see ___ dog", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: He is ___ engineer", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: ___ car is red", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: She bought ___ dress", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: This is ___ orange", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: ___ book on the table is mine", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: I have ___ idea", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: He found ___ key", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: ___ moon is bright", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: She is ___ artist", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: I need ___ pen", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: ___ teacher is in the room", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: He ate ___ banana", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },
{ q: "Complete: This is ___ old house", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: ___ door is closed", target: "ARTICLE", a: "the", opts: ["a", "an", "the"] },
{ q: "Complete: I saw ___ elephant", target: "ARTICLE", a: "an", opts: ["a", "an", "the"] },
{ q: "Complete: She has ___ bike", target: "ARTICLE", a: "a", opts: ["a", "an", "the"] },

{ q: "Complete: I ___ now", target: "EAT", a: "am eating", opts: ["eat", "ate", "am eating"] },
{ q: "Complete: She ___ now", target: "EAT", a: "is eating", opts: ["eat", "eats", "is eating"] },

{ q: "Complete: I ___ ready", target: "BE", a: "am", opts: ["am", "is", "are"] },
{ q: "Complete: They ___ ready", target: "BE", a: "are", opts: ["am", "is", "are"] },

{ q: "Complete: I ___ tomorrow", target: "GO", a: "will go", opts: ["go", "went", "will go"] },
{ q: "Complete: She ___ tomorrow", target: "COME", a: "will come", opts: ["comes", "came", "will come"] },
{ q: "Complete: I ___ working all day", target: "BE", a: "have been", opts: ["am", "was", "have been"] },
{ q: "Complete: She ___ working all night", target: "BE", a: "has been", opts: ["is", "was", "has been"] },

{ q: "Complete: I ___ never seen this", target: "SEE", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ never seen this", target: "SEE", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ already finished", target: "FINISH", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: She ___ already finished", target: "FINISH", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ just arrived", target: "ARRIVE", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ just arrived", target: "ARRIVE", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ been there before", target: "BE", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: She ___ been there before", target: "BE", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ going to travel", target: "BE", a: "am", opts: ["am", "is", "are"] },
{ q: "Complete: They ___ going to travel", target: "BE", a: "are", opts: ["am", "is", "are"] },

{ q: "Complete: I ___ go tomorrow", target: "WILL", a: "will", opts: ["will", "went", "going"] },
{ q: "Complete: She ___ come later", target: "WILL", a: "will", opts: ["will", "comes", "came"] },

{ q: "Complete: I ___ been waiting for hours", target: "BE", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ been waiting for hours", target: "BE", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ not finished yet", target: "FINISH", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: She ___ not finished yet", target: "FINISH", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ already eaten", target: "EAT", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ already eaten", target: "EAT", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ been studying English", target: "STUDY", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: She ___ been studying English", target: "STUDY", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ done this before", target: "DO", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ done this before", target: "DO", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ working when you called", target: "BE", a: "was", opts: ["am", "was", "were"] },
{ q: "Complete: They ___ working when you called", target: "BE", a: "were", opts: ["am", "was", "were"] },

{ q: "Complete: I ___ go if I had time", target: "WILL", a: "would", opts: ["will", "would", "going"] },
{ q: "Complete: She ___ go if she had money", target: "WILL", a: "would", opts: ["will", "would", "went"] },

{ q: "Complete: I ___ have done that", target: "CAN", a: "could", opts: ["can", "could", "will"] },
{ q: "Complete: He ___ have done that", target: "CAN", a: "could", opts: ["can", "could", "does"] },

{ q: "Complete: I ___ finish this today", target: "MUST", a: "must", opts: ["must", "may", "might"] },
{ q: "Complete: She ___ finish this today", target: "MUST", a: "must", opts: ["must", "may", "might"] },

{ q: "Complete: I ___ be late", target: "MIGHT", a: "might", opts: ["must", "might", "will"] },
{ q: "Complete: He ___ be late", target: "MIGHT", a: "might", opts: ["must", "might", "does"] },

{ q: "Complete: I ___ have forgotten", target: "MAY", a: "may", opts: ["may", "must", "will"] },
{ q: "Complete: She ___ have forgotten", target: "MAY", a: "may", opts: ["may", "does", "is"] },

{ q: "Complete: I ___ not go", target: "SHOULD", a: "should", opts: ["should", "must", "will"] },
{ q: "Complete: He ___ not go", target: "SHOULD", a: "should", opts: ["should", "does", "is"] },

{ q: "Complete: I ___ been there", target: "HAVE", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: She ___ been there", target: "HAVE", a: "has", opts: ["have", "has", "had"] },

{ q: "Complete: I ___ known this before", target: "KNOW", a: "have", opts: ["have", "has", "had"] },
{ q: "Complete: He ___ known this before", target: "KNOW", a: "has", opts: ["have", "has", "had"] },
{ q: "Complete: She is ___ home", target: "PREPOSITION", a: "at", opts: ["in", "on", "at"] },
{ q: "Complete: The book is ___ the table", target: "PREPOSITION", a: "on", opts: ["in", "on", "at"] },
{ q: "Complete: The cat is ___ the box", target: "PREPOSITION", a: "in", opts: ["in", "on", "under"] },
{ q: "Complete: He is ___ the car", target: "PREPOSITION", a: "in", opts: ["in", "on", "at"] },
{ q: "Complete: The dog is ___ the chair", target: "PREPOSITION", a: "under", opts: ["under", "on", "above"] },
{ q: "Complete: She is ___ the door", target: "PREPOSITION", a: "behind", opts: ["behind", "on", "in"] },
{ q: "Complete: The ball is ___ the box", target: "PREPOSITION", a: "in", opts: ["in", "on", "at"] },
{ q: "Complete: He is ___ school", target: "PREPOSITION", a: "at", opts: ["at", "in", "on"] },
{ q: "Complete: She is ___ the room", target: "PREPOSITION", a: "in", opts: ["on", "in", "at"] },
{ q: "Complete: The keys are ___ the table", target: "PREPOSITION", a: "on", opts: ["in", "on", "under"] },
{ q: "Complete: The cat is ___ the table", target: "PREPOSITION", a: "under", opts: ["under", "on", "in"] },
{ q: "Complete: He is ___ his friend", target: "PREPOSITION", a: "with", opts: ["with", "in", "on"] },
{ q: "Complete: She goes ___ school", target: "PREPOSITION", a: "to", opts: ["to", "in", "at"] },
{ q: "Complete: He comes ___ Brazil", target: "PREPOSITION", a: "from", opts: ["from", "to", "at"] },
{ q: "Complete: The picture is ___ the wall", target: "PREPOSITION", a: "on", opts: ["in", "on", "at"] },
{ q: "Complete: The lamp is ___ the table", target: "PREPOSITION", a: "on", opts: ["under", "on", "in"] },
{ q: "Complete: The cat is ___ the sofa", target: "PREPOSITION", a: "on", opts: ["on", "in", "under"] },
{ q: "Complete: He sits ___ me", target: "PREPOSITION", a: "next to", opts: ["next to", "under", "above"] },
{ q: "Complete: The store is ___ the bank", target: "PREPOSITION", a: "next to", opts: ["next to", "in", "on"] },
{ q: "Complete: The car is ___ the house", target: "PREPOSITION", a: "in front of", opts: ["behind", "in front of", "under"] },
 { q: "Complete: I ___ every day", target: "TRY", a: "try", opts: ["try", "tries", "trying"] },
{ q: "Complete: He ___ again", target: "TRY", a: "tries", opts: ["try", "tries", "trying"] },
{ q: "Complete: She ___ to learn", target: "TRY", a: "tries", opts: ["try", "tries", "trying"] },
{ q: "Complete: They ___ together", target: "TRY", a: "try", opts: ["try", "tries", "trying"] },
{ q: "Complete: We ___ to win", target: "TRY", a: "try", opts: ["try", "tries", "trying"] },
{ q: "Complete: It ___ to move", target: "TRY", a: "tries", opts: ["try", "tries", "trying"] },
{ q: "Complete: You ___ your best", target: "TRY", a: "try", opts: ["try", "tries", "trying"] },
{ q: "Complete: He ___ every time", target: "TRY", a: "tries", opts: ["try", "tries", "trying"] },
{ q: "Complete: She ___ again and again", target: "TRY", a: "tries", opts: ["try", "tries", "trying"] },
{ q: "Complete: I ___ to understand", target: "TRY", a: "try", opts: ["try", "tries", "trying"] },
{ q: "Complete: The ball is ___ the boxes", target: "PREPOSITION", a: "between", opts: ["between", "among", "under"] },
{ q: "Complete: She ___ between her parents", target: "SIT", a: "sits", opts: ["sit", "sits", "sitting"] },
{ q: "Complete: Choose a number ___ one and ten", target: "PREPOSITION", a: "between", opts: ["between", "at", "on"] },
{ q: "Complete: They ___ between the buildings", target: "WALK", a: "walk", opts: ["walk", "walks", "walking"] },
{ q: "Complete: The river ___ between the mountains", target: "FLOW", a: "flows", opts: ["flow", "flows", "flowing"] },
{ q: "Complete: He ___ between the cars yesterday", target: "STAND", a: "stood", opts: ["stand", "stands", "stood"] },
{ q: "Complete: There is a wall ___ our houses", target: "PREPOSITION", a: "between", opts: ["between", "from", "to"] },
{ q: "Complete: The cat ___ between the pillows", target: "SLEEP", a: "sleeps", opts: ["sleep", "sleeps", "sleeping"] },
{ q: "Complete: I am ___ between you and the door", target: "STAY", a: "staying", opts: ["stay", "stays", "staying"] },
{ q: "Complete: We ___ a gap between the curtains", target: "SEE", a: "saw", opts: ["see", "sees", "saw"] },
{ q: "Complete: Meet me ___ 8 AM and 9 AM", target: "PREPOSITION", a: "between", opts: ["between", "after", "before"] },
{ q: "Complete: Please ___ the paper between the pages", target: "PUT", a: "put", opts: ["put", "puts", "putting"] },
{ q: "Complete: The coin ___ between the seats", target: "FALL", a: "fell", opts: ["fall", "falls", "fell"] },
{ q: "Complete: We ___ between two big cities", target: "LIVE", a: "live", opts: ["live", "lives", "living"] },
{ q: "Complete: The plane ___ between the clouds", target: "FLY", a: "flies", opts: ["fly", "flies", "flying"] },
{ q: "Complete: Don't ___ between those two cars", target: "PARK", a: "park", opts: ["park", "parks", "parking"] },
{ q: "Complete: I must ___ between these two options", target: "CHOOSE", a: "choose", opts: ["choose", "chooses", "chosen"] },
{ q: "Complete: He ___ a secret between us", target: "KEEP", a: "kept", opts: ["keep", "keeps", "kept"] },
{ q: "Complete: The link ___ the events is clear", target: "PREPOSITION", a: "between", opts: ["between", "with", "of"] },
{ q: "Complete: I will ___ for you between 5 and 6", target: "WAIT", a: "wait", opts: ["wait", "waits", "waiting"] },
{ q: "Complete: ___! How are you?", target: "HELLO", a: "hello", opts: ["hello", "wow", "ouch"] },
{ q: "Complete: ___! That’s amazing!", target: "WOW", a: "wow", opts: ["wow", "ugh", "oops"] },
{ q: "Complete: ___! I hurt my arm!", target: "OUCH", a: "ouch", opts: ["ouch", "yay", "hello"] },
{ q: "Complete: ___! I forgot my keys!", target: "OOPS", a: "oops", opts: ["oops", "hi", "bravo"] },
{ q: "Complete: ___! We won the game!", target: "YAY", a: "yay", opts: ["yay", "ugh", "huh"] },
{ q: "Complete: ___! Be quiet, please.", target: "SHH", a: "shh", opts: ["shh", "wow", "yo"] },
{ q: "Complete: ___! I don’t understand.", target: "HUH", a: "huh", opts: ["huh", "yay", "hello"] },
{ q: "Complete: ___! That’s disgusting!", target: "YUCK", a: "yuck", opts: ["yuck", "wow", "hi"] },
{ q: "Complete: ___! Come here for a second.", target: "HEY", a: "hey", opts: ["hey", "ouch", "ugh"] },
{ q: "Complete: ___! Finally finished!", target: "AH", a: "ah", opts: ["ah", "oops", "psst"] }
];


